MAX_VOICE_WORDS = 75
TTS_PROVIDER_TIMEOUT = 45

ELEVENLAB = "elevenlab"
FINEVOICE = "finevoice"
OPENROUTER = "openrouter"

DEFAULT_ELEVENLAB_MODEL = "eleven_multilingual_v2"
DEFAULT_ELEVENLAB_VOICE = "21m00Tcm4TlvDq8ikWAM"
DEFAULT_FINEVOICE_VOICE = "james"
DEFAULT_OPENROUTER_TTS_MODEL = "x-ai/grok-voice-tts-1.0"
DEFAULT_OPENROUTER_TTS_VOICE = "Eve"
